export const FETCH_WEATHER = '@WEATHER/FETCH'
export const FETCH_WEATHER_CANCEL = '@WEATHER/CANCEL'
export const FETCH_WEATHER_FULFILLED = '@WEATHER/FULFILLED'
export const FETCH_WEATHER_REJECTED = '@WEATHER/REJECTED'
